name:                slate
version:             0.6.0.0
github:              "evuez/slate"
license:             MIT
author:              "evuez"
maintainer:          "helloevuez@gmail.com"
copyright:           "Copyright (c) 2017, evuez"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            A note taking CLI tool.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/evuez/slate#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.14
- directory >= 1.3
- filepath >= 1.4
- process >= 1.6
- htoml >= 1.0
- unordered-containers >= 0.2
- string-conversions >= 0.2

library:
  source-dirs: src

executables:
  slate:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slate

tests:
  slate-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - slate
